"use strict";

var cmd_or_ctrl = (process.platform === "darwin") ? "Cmd" : "Ctrl";

exports.menu = {
  "new":   { key: "N", modifiers: cmd_or_ctrl },
  "open":   { key: "O", modifiers: cmd_or_ctrl },
  "save":   { key: "S", modifiers: cmd_or_ctrl },
  "saveas": { key: "S", modifiers: cmd_or_ctrl + "+Shift" },
  "print":  { key: "P", modifiers: cmd_or_ctrl + "+Shift" },
  "message" : { key: "M", modifiers: cmd_or_ctrl },
  "close":  { key: "W", modifiers: cmd_or_ctrl },
  "quit":   { key: "Q", modifiers: cmd_or_ctrl },

  "undo":   { key: "Z", modifiers: cmd_or_ctrl },
  "redo":   { key: "Z", modifiers: cmd_or_ctrl + "+Shift" },
  "selectall":{ key: "A", modifiers: cmd_or_ctrl },
  "cut":    { key: "X", modifiers: cmd_or_ctrl },
  "copy":   { key: "C", modifiers: cmd_or_ctrl },
  "paste":  { key: "V", modifiers: cmd_or_ctrl },
  "paste_clipboard": { key: "V", modifiers: cmd_or_ctrl + "+Alt" },
  "duplicate": { key: "D", modifiers: cmd_or_ctrl },
  "undo":   { key: "Z", modifiers: cmd_or_ctrl },

  "reselect": { key: String.fromCharCode(10), modifiers: cmd_or_ctrl },
  "clear_console": { key: "L", modifiers: cmd_or_ctrl + "+Shift" },
  "tidyup": { key: "Y", modifiers: cmd_or_ctrl },
  "cordinspector":   { key: "R", modifiers: cmd_or_ctrl + "+Shift" },
  "find":   { key: "F", modifiers: cmd_or_ctrl },
  "findagain":{ key: "G", modifiers: cmd_or_ctrl },
  "editmode": { key: "E", modifiers: cmd_or_ctrl },
  "preferences": { key: (process.platform === "darwin") ? "," : "P",
    modifiers: cmd_or_ctrl },

  "zoomin": { key: "=", modifiers: cmd_or_ctrl },
  "zoomout": { key: "-", modifiers: cmd_or_ctrl },
  "zoomreset": { key: "0", modifiers: cmd_or_ctrl },
  "zoomoptimal": { key: "9", modifiers: cmd_or_ctrl },
  "zoomhoriz": { key: "9", modifiers: cmd_or_ctrl + "+Alt" },
  "zoomvert": { key: "9", modifiers: cmd_or_ctrl + "+Shift" },
  "fullscreen": { key: (process.platform === "darwin") ? "F" : "F11",
    modifiers: (process.platform === "darwin") ? "Cmd+Ctrl" : "null" },

  "object": { key: "1", modifiers: cmd_or_ctrl },
  "msgbox": { key: "2", modifiers: cmd_or_ctrl },
  "number": { key: "3", modifiers: cmd_or_ctrl },
  "symbol": { key: "4", modifiers: cmd_or_ctrl },
  "comment": { key: "5", modifiers: cmd_or_ctrl },
  "dropdown": { key: "6", modifiers: cmd_or_ctrl },
  "bang": { key: "B", modifiers: cmd_or_ctrl + "+Shift" },
  "toggle": { key: "T", modifiers: cmd_or_ctrl + "+Shift" },
  "number2": { key: "N", modifiers: cmd_or_ctrl + "+Shift" },
  "vslider": { key: "V", modifiers: cmd_or_ctrl + "+Shift" },
  "hslider": { key: "H", modifiers: cmd_or_ctrl + "+Shift" },
  "vradio": { key: "D", modifiers: cmd_or_ctrl + "+Shift" },
  "hradio": { key: "I", modifiers: cmd_or_ctrl + "+Shift" },
  "vu":     { key: "U", modifiers: cmd_or_ctrl + "+Shift" },
  "cnv": { key: "C", modifiers: cmd_or_ctrl + "+Shift" },

  "nextwin": { key: "PageDown", modifiers: cmd_or_ctrl },
  "prevwin": { key: "PageUp", modifiers: cmd_or_ctrl },
  "pdwin": { key: "R", modifiers: cmd_or_ctrl },

  "audio_on": { key: "/", modifiers: cmd_or_ctrl },
  "audio_off": { key: ".", modifiers: cmd_or_ctrl },

  "browser": { key: "B", modifiers: cmd_or_ctrl },
  "audio_off": { key: ".", modifiers: cmd_or_ctrl },
  "audio_off": { key: ".", modifiers: cmd_or_ctrl },
  "audio_off": { key: ".", modifiers: cmd_or_ctrl },


  // Webapp shortcuts
  "new_web":   { key: "N", modifiers: cmd_or_ctrl + "+Alt"},
  "open_web":   { key: "O", modifiers: cmd_or_ctrl + "+Alt"},
  "save_web":   { key: "S", modifiers: cmd_or_ctrl + "+Alt" },
  "saveas_web": { key: "S", modifiers: cmd_or_ctrl + "+Shift" },
  "print_web":  { key: "P", modifiers: cmd_or_ctrl + "+Alt" },
  "message_web" : { key: "M", modifiers: cmd_or_ctrl + "+Alt"},
  "close_web":  { key: "W", modifiers: cmd_or_ctrl + "+Alt" },

  "undo_web":   { key: "Z", modifiers: cmd_or_ctrl + "+Alt" },
  "redo_web":   { key: "Z", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "selectall_web":{ key: "Q", modifiers: cmd_or_ctrl + "+Shift"},
  "cut_web":    { key: "X", modifiers: cmd_or_ctrl + "+Shift" },
  "copy_web":   { key: "C", modifiers: cmd_or_ctrl + "+Alt"},
  "paste_web":  { key: "V", modifiers: cmd_or_ctrl + "+Alt" },
  "paste_clipboard_web": { key: "G", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "duplicate_web": { key: "D", modifiers: cmd_or_ctrl + "+Alt" },

  "reselect_web": { key: "Q", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "clear_console_web": { key: "L", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "tidyup_web": { key: "Y", modifiers: cmd_or_ctrl + "+Alt" },
  "cordinspector_web":   { key: "R", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "find_web":   { key: "F", modifiers: cmd_or_ctrl + "+Alt"},
  "findagain_web":{ key: "F", modifiers: cmd_or_ctrl + "+Shift+Alt"},
  "editmode_web": { key: "E", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "preferences_web": { key: (process.platform === "darwin") ? "," : "P",
    modifiers: cmd_or_ctrl },

  "zoomin_web": { key: "=", modifiers: cmd_or_ctrl },
  "zoomout_web": { key: "-", modifiers: cmd_or_ctrl },
  "zoomreset_web": { key: "0", modifiers: cmd_or_ctrl },
  "zoomoptimal_web": { key: "9", modifiers: cmd_or_ctrl },
  "zoomhoriz_web": { key: "9", modifiers: cmd_or_ctrl + "+Alt" },
  "zoomvert_web": { key: "9", modifiers: cmd_or_ctrl + "+Shift" },
  "fullscreen_web": { key: (process.platform === "darwin") ? "F" : "F11",
    modifiers: (process.platform === "darwin") ? "Cmd+Ctrl" : "null" },

  "object_web": { key: "1", modifiers: cmd_or_ctrl + "+Alt" },
  "msgbox_web": { key: "2", modifiers: cmd_or_ctrl + "+Alt" },
  "number_web": { key: "3", modifiers: cmd_or_ctrl + "+Alt" },
  "symbol_web": { key: "4", modifiers: cmd_or_ctrl + "+Alt" },
  "comment_web": { key: "5", modifiers: cmd_or_ctrl + "+Alt" },
  "dropdown_web": { key: "m", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "bang_web": { key: "B", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "toggle_web": { key: "T", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "number2_web": { key: "N", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "vslider_web": { key: "V", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "hslider_web": { key: "H", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "vradio_web": { key: "D", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "hradio_web": { key: "I", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "vu_web":     { key: "U", modifiers: cmd_or_ctrl + "+Shift+Alt" },
  "cnv_web": { key: "C", modifiers: cmd_or_ctrl + "+Shift+Alt" },

  "nextwin_web": { key: "PageDown", modifiers: cmd_or_ctrl + "+Alt"},
  "prevwin_web": { key: "PageUp", modifiers: cmd_or_ctrl + "+Alt"},
  "pdwin_web": { key: "R", modifiers: cmd_or_ctrl },

  "audio_on_web": { key: "/", modifiers: cmd_or_ctrl + "+Alt"},
  "audio_off_web": { key: ".", modifiers: cmd_or_ctrl + "+Alt"},

  "browser_web": { key: "B", modifiers: cmd_or_ctrl + "+Alt" },

}
